apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-pvc
  labels:
    tier: storage
    app: app-storage
spec:
  storageClassName: storageclass-nfs-dynamic
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
