apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  storageClassName: storageclass-nfs # SAME NAME AS THE STORAGECLASS
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 100Mi
