{
 "title": "ec2",
 "tags": [ "prometheus" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Avg CPU utilization per instance [max %]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_ec2_cpuutilization_average{instance_id=~\"i-.*\"}",
     "legendFormat": "{{ instance_id }}"
    }
   ]
  },
  {
   "title": "Avg Inbound network traffic per instance [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_ec2_network_in_average{instance_id=~\"i-.*\"}",
     "legendFormat": "{{ instance_id }}"
    }
   ]
  },
  {
   "title": " Avg Outbound network traffic per instance [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_ec2_network_out_average{instance_id=~\"i-.*\"}",
     "legendFormat": "{{ instance_id }}"
    }
   ]
  }
 ]
}