{
 "title": "elb",
 "tags": [ "prometheus" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "avazone",
    "label": "Availability Zone",
    "query": "label_values(availability_zone)"
   },
   {
    "name": "load",
    "label": "LoadBalancer Name",
    "query": "label_values(load_balancer_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "SurgeQueueLength(Sum/Max)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elb_surge_queue_length_sum{load_balancer_name=~\"$load\",availability_zone=~\"$avazone\"}",
     "legendFormat": "SurgeQueueLength_Sum"
    },
    {
     "expr": "aws_elb_surge_queue_length_maximum{load_balancer_name=~\"$load\",availability_zone=~\"$avazone\"}",
     "legendFormat": "SurgeQueueLength_Maximum"
    }
   ]
  },
  {
   "title": "Request Count/Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aws_elb_request_count_sum{load_balancer_name=~\"$load\",availability_zone=~\"$avazone\"}",
     "legendFormat": "Request_Count_Sum"
    },
    {
     "expr": "aws_elb_latency_average{load_balancer_name=~\"$load\",availability_zone=~\"$avazone\"}",
     "legendFormat": "Latency_Average"
    }
   ]
  },
  {
   "title": "Host Count (Healthy/Unhealthy)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elb_healthy_host_count_average{load_balancer_name=~\"$load\",availability_zone=~\"$avazone\"}",
     "legendFormat": "HealthyHostCount"
    },
    {
     "expr": "aws_elb_un_healthy_host_count_average{load_balancer_name=~\"$load\",availability_zone=~\"$avazone\"}",
     "legendFormat": "UnhealthyHostCount"
    }
   ]
  }
 ]
}