# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  password:
  user:
  database:
  basicAuth: true
  basicAuthUser: admin
  basicAuthPassword: admin
  withCredentials:
  isDefault:
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  editable: true
- name: InfluxDB
  type: influxdb
  access: proxy
  url: "http://influxdb:8086"
  password: admin
  user: admin
  database:
  basicAuth: false
- name: Cloudwatch
  type: cloudwatch
  jsonData:
    authType: credentials
    defaultRegion: us-east-2
